### ISSUE TITLE
[Bug] Unsupported data type 'VARIANT' for iceberg tables

### ISSUE THREAD

**Issue by annmat88** [dbt-labs/dbt-adapters#1683]
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Which packages are affected?

- [ ] dbt-adapters
- [ ] dbt-tests-adapter
- [ ] dbt-athena
- [ ] dbt-athena-community
- [ ] dbt-bigquery
- [ ] dbt-postgres
- [ ] dbt-redshift
- [x] dbt-snowflake
- [ ] dbt-spark

### Current Behavior

Getting the error **"Unsupported data type 'VARIANT' for iceberg tables "** on the latest version of DBT cloud and the same succeeds when running on a lower version like 1.7

### Expected Behavior

DBT run should succeed in the latest version just like it works on 1.7 version 

### Steps To Reproduce

Create an iceberg table with the below select statement
    SELECT
                METADATA$FILENAME AS META_FILENAME,
                METADATA$FILE_ROW_NUMBER AS META_FILE_ROW_NUMBER,
                $1::VARIANT AS JSON_DATA
and the source file format is parquet.

This should work on the latest version of dbt cloud. Currently it is working only on lower versions like 1.7

### Relevant log output

```shell
091386 (42601): SQL Compilation error:
  Unsupported data type 'VARIANT' for iceberg tables.
```

### Environment

```markdown
dbt cloud latest version
```

**Comment by annmat88** [comment]
Hi is there any update on this issue?
