### ISSUE TITLE
incremental materializations/sql failing on an Iceberg REST with Snowflake CLD

### ISSUE THREAD

**Issue by ghost** [dbt-labs/dbt-adapters#1459]
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Which packages are affected?

- [x] dbt-adapters
- [ ] dbt-tests-adapter
- [ ] dbt-athena
- [ ] dbt-athena-community
- [ ] dbt-bigquery
- [ ] dbt-postgres
- [ ] dbt-redshift
- [x] dbt-snowflake
- [ ] dbt-spark

### Current Behavior

[community slack thread](https://getdbt.slack.com/archives/C07P3K1NN7N/p1763453979040649)

Incremental materializations are trying to create temp views in a snowflake catalog linked database (CLD) and it is crashing - as CLD does not support creating temp views
`create or replace temporary view <my model>__dbt_tmp`

Snowflake error: 
`SQL Compilation Error: This operation is not supported in a catalog-linked database.
`

Full refresh works fine

This issue was already mentioned below, but it does not seem to have been fixed in all cases:
https://github.com/dbt-labs/dbt-adapters/pull/1287

My setup:
  - dbt-core: `1.11.0-b4`
  - dbt-snowflake: `1.10.2`
  - Target: Iceberg tables in catalog-linked database with external Polaris catalog

My `catalogs.yml `- the only difference in mime compared to the docs are:
```
catalog_type: iceberg_rest
adapter_properties:
  auto_refresh: True
  target_file_size: 128MB
  catalog_linked_database: <my_CLD>
```

Thanks

### Expected Behavior

Incremental materializations run without error

### Steps To Reproduce

 Run an incremental materialization on snowflake catalog-linked database targetting iceberg tables (catalog = Snowflake Polaris)

### Relevant log output

```shell

```

### Environment

```markdown
- OS:
- Python:
- dbt-adapters:
- <adapter>:
```

**Comment by dataders** [comment]
related to #1377 in that maybe it doesn't completely fix things

**Comment by ghost** [comment]
confirmed working in version `dbt-snowflake==1.11.0b1`

**Comment by VersusFacit** [comment]
Excellent. @ajhlee-dbt and I tried to repro on the newest release and no error. Thanks for your comment, I think we can close this one :)
