### ISSUE TITLE
[Bug] [Snowflake] validate_doc_columns is undefined after upgrading to 1.11.6

### ISSUE THREAD

**Issue by moseleyi** [dbt-labs/dbt-adapters#2043]
### Is this a new bug?

- [x] I believe this is a new bug
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Which packages are affected?

- [ ] dbt-adapters
- [ ] dbt-tests-adapter
- [ ] dbt-athena
- [ ] dbt-athena-community
- [ ] dbt-bigquery
- [ ] dbt-postgres
- [ ] dbt-redshift
- [x] dbt-snowflake
- [ ] dbt-spark

### Current Behavior

When a model has description on itself or one of its columns, it's not possible to build the model due to an error:

```
  Compilation Error in model dim_selling_rates (models\transformations\dsr.sql)
  'validate_doc_columns' is undefined
  
  > in macro alter_column_comment (macros\adapters\persist_docs.sql)
  > called by macro snowflake__persist_docs (macros\adapters.sql)
  > called by macro persist_docs (macros\adapters\persist_docs.sql)
  > called by macro materialization_incremental_snowflake (macros\materializations\incremental.sql)
  > called by model dim_selling_rates (models\transformations\dsr.sql)
08:50:40  
08:50:40    compiled code at target\compiled\adpf\models\transformations\dsr.sql
08:50:40  
08:50:40  Done. PASS=0 WARN=0 ERROR=1 SKIP=2 NO-OP=0 TOTAL=3
```

If I downgrade to `1.11.3` it works again

### Expected Behavior

model built successfully

### Steps To Reproduce

1. Install `dbt-snowflake` `1.11.6`
2. Add sample model
3. Add description to the model in YAML file
4. Run `dbt build`

### Relevant log output

```shell

```

### Environment

```markdown
- OS: Windows Home
- Python: 3.12.3
- dbt-core: 1.11.11
- dbt-snowflae: 1.11.6
```

**Comment by matt-chequers-convictional** [comment]
Similar thing was happening for me, using bigquery though.

- `dbt-core`: 1.11.12
- `dbt-bigquery`: 1.11.3

What I found:

In 1.11.3, `dbt-bigquery` started calling a new helper (`validate_doc_columns`) that lives in `dbt-adapters`, but that helper only exists in `dbt-adapters` 1.22.10+. `dbt-bigquery` 1.11.3 shipped with a dependency floor that's too low (>=1.22.6), so my lockfile was allowed to keep an older `dbt-adapters` (1.22.7) that predates the helper.

My fix was to add `dbt-adapters` explicitly as a dependency (instead of implicitly via `dbt-biguqery`). Setting it to 1.24.4 (latest) fixed this issue for me. 

Similar thing could be happening for you with `dbt-snowflake` maybe?

**Comment by moseleyi** [comment]
I suspected this is a bug with dependencies and that somebody didn't pay attention when upgrading all the different packages. 

At the moment I just reverted back and will wait for a fix..
